model_params:
  name: 'SiFall'
  in_channels: 3
  latent_dim: 128


data_params:
  data_path: "data/snow_jacket_azi_fft.v9.1/"
  train_batch_size: 32
  val_batch_size: 32
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 0

trainer_params:
  gpus: [ 0 ]
  max_epochs: 162
  check_val_every_n_epoch: 5

logging_params:
  save_dir: "logs/"
  name: "SiFall"

